apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: cnn-deployment
  name: cnnsvc
spec:
  ports:
  - nodePort: 31030
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app.kubernetes.io/name: cnn-deployment
  sessionAffinity: None
  type: LoadBalancer