apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: controller-rc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controller-node
  template:
    metadata:
      labels:
        app: controller-node
    spec:
      containers:
      - name: controller-node
        image: edwardbafford/ml-controller