apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: controller-deployment
  name: controller-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: controller-deployment
  template:
    metadata:
      labels:
        app.kubernetes.io/name: controller-deployment
    spec:
      containers:
      - image: edwardbafford/ml-controller:latest
        name: controller-node
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/etc/key/api-key.json"
        volumeMounts:
        - name: google-key
          mountPath: "/etc/key"
          readOnly: true
      volumes:
      - name: google-key
        secret:
          secretName: google-api-key