apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: cnn-deployment
  name: cnn-deployment
spec:
  replicas: {{ .Values.cnn.deployment.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: cnn-deployment
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cnn-deployment
    spec:
      containers:
      - image: edwardbafford/ml-cnn
        name: cnn-node
        ports:
        - containerPort: {{ .Values.cnn.port }}
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/etc/key/api-key.json"
        volumeMounts:
        - name: google-key
          mountPath: "/etc/key"
          readOnly: true
      volumes:
      - name: google-key
        secret:
          secretName: google-api-key